from __future__ import annotations

import csv
import json
from io import BytesIO
from html import escape
from math import acos, degrees, hypot
from pathlib import Path

from .fabrication_data import Panel2D
from .geometry_2d import polygon_bounds


SVG_LAYERS = ["CUT", "ENGRAVE", "FOLD", "V_GROOVE", "LIVING_HINGE", "HOLES", "MAGNETS", "SCREWS", "LABELS", "SUPPORTS", "CONNECTORS", "WARNINGS"]


def export_svg(path: str | Path, panels: list[Panel2D], width: float, height: float) -> None:
    path = Path(path)
    rows = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}mm" height="{height}mm" viewBox="0 0 {width} {height}">',
        "<style>.cut{fill:none;stroke:#d00;stroke-width:0.1}.hole{fill:none;stroke:#06c;stroke-width:0.1}.label{font:4px sans-serif;fill:#111}</style>",
    ]
    for layer in SVG_LAYERS:
        rows.append(f'<g id="{layer}">')
        if layer == "CUT":
            for p in panels:
                d = " ".join(f"{x:.3f},{y:.3f}" for x, y in p.points)
                rows.append(f'<polygon class="cut" points="{d}" data-id="{p.panel_id}" data-material="{p.material}"/>')
        if layer in {"HOLES", "MAGNETS", "SCREWS"}:
            for p in panels:
                for hole in p.holes:
                    if hole.get("layer", "HOLES") != layer:
                        continue
                    if hole["type"] == "CIRCLE":
                        rows.append(f'<circle class="hole" cx="{hole["x"]:.3f}" cy="{hole["y"]:.3f}" r="{hole["r"]:.3f}"/>')
                    elif hole["type"] == "RECTANGLE":
                        rows.append(f'<rect class="hole" x="{hole["x"]:.3f}" y="{hole["y"]:.3f}" width="{hole["w"]:.3f}" height="{hole["h"]:.3f}"/>')
        if layer == "LABELS":
            for p in panels:
                x, y = p.points[0]
                rows.append(f'<text class="label" x="{x:.3f}" y="{y:.3f}">{p.panel_id} {p.material}</text>')
        rows.append("</g>")
    rows.append("</svg>")
    path.write_text("\n".join(rows), encoding="utf-8")


def export_annotated_svg(path: str | Path, panels: list[Panel2D], width: float, height: float, title: str = "Fabrication Layout") -> None:
    rows = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}mm" height="{height + 58}mm" viewBox="0 0 {width} {height + 58}">',
        """<style>
.sheet{fill:#fff}.title{font:700 9px Arial;fill:#111}.meta{font:4px Arial;fill:#444}
.cut{fill:#fff;stroke:#d71920;stroke-width:.35}.hole{fill:none;stroke:#0066b3;stroke-width:.25}
.label{font:700 4px Arial;fill:#111}.tiny{font:3px Arial;fill:#333}.edge{font:3px Arial;fill:#d71920}
.dim{stroke:#111;stroke-width:.15;marker-start:url(#arrow);marker-end:url(#arrow)}.dimtext{font:3px Arial;fill:#111}
.legend{font:3.5px Arial;fill:#111}.box{fill:#f7f7f7;stroke:#111;stroke-width:.25}
</style>""",
        '<defs><marker id="arrow" markerWidth="4" markerHeight="4" refX="2" refY="2" orient="auto"><path d="M0,0 L4,2 L0,4 z" fill="#111"/></marker></defs>',
        f'<rect class="sheet" x="0" y="0" width="{width}" height="{height + 58}"/>',
        f'<text class="title" x="10" y="13">{escape(title)}</text>',
        f'<text class="meta" x="10" y="21">Scale: 1 SVG unit = 1 mm | Parts: {len(panels)} | Generated by LowPoly Fabrication Toolkit</text>',
        '<rect class="box" x="10" y="27" width="118" height="20" rx="2"/>',
        '<text class="legend" x="15" y="35">CUT red outlines</text><text class="legend" x="15" y="42">HOLES blue outlines</text>',
        '<text class="legend" x="72" y="35">Edge numbers: red</text><text class="legend" x="72" y="42">Angles/dimensions: black</text>',
        '<g transform="translate(0 58)">',
    ]
    for index, panel in enumerate(panels, 1):
        rows.extend(_annotated_panel(panel, index))
    rows += ["</g>", "</svg>"]
    Path(path).write_text("\n".join(rows), encoding="utf-8")


def export_canva_layout_board(path: str | Path, annotated_svg_name: str = "layout_annotated.svg") -> None:
    html = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Canva Fabrication Layout Board</title>
<style>
@page {{ size: 16in 9in; margin: 0; }}
body {{ margin: 0; font-family: Arial, sans-serif; background: #f0f0f0; }}
.page {{ width: 16in; height: 9in; background: white; padding: .35in; box-sizing: border-box; }}
h1 {{ margin: 0 0 .12in; font-size: 34px; }}
.frame {{ border: 4px solid #111; height: 7.55in; display: grid; place-items: center; background: #fafafa; }}
.note {{ margin-top: .12in; font-size: 13px; color: #555; }}
</style>
</head>
<body>
<section class="page">
<h1>Fabrication Layout Board</h1>
<div class="frame">PLACE / UPLOAD {escape(annotated_svg_name)} HERE</div>
<p class="note">Use this Canva page as the polished presentation sheet. Import the SVG as vector art, then add renders, warnings, and customer-facing notes.</p>
</section>
</body>
</html>
"""
    Path(path).write_text(html, encoding="utf-8")


def _annotated_panel(panel: Panel2D, index: int) -> list[str]:
    points = panel.points
    if not points:
        return []
    rows = []
    d = " ".join(f"{x:.3f},{y:.3f}" for x, y in points)
    rows.append(f'<polygon class="cut" points="{d}" data-id="{escape(panel.panel_id)}"/>')
    cx = sum(x for x, _ in points) / len(points)
    cy = sum(y for _, y in points) / len(points)
    rows.append(f'<text class="label" x="{cx:.3f}" y="{cy:.3f}" text-anchor="middle">{index}. {escape(panel.panel_id)}</text>')
    rows.append(f'<text class="tiny" x="{cx:.3f}" y="{cy + 5:.3f}" text-anchor="middle">{escape(panel.material)} | {panel.thickness:g}mm</text>')
    rows.extend(_edge_labels(points))
    rows.extend(_angle_labels(points))
    rows.extend(_dimension_labels(points))
    rows.extend(_hole_shapes(panel.holes))
    return rows


def _edge_labels(points: list[tuple[float, float]]) -> list[str]:
    labels = []
    for i, ((x1, y1), (x2, y2)) in enumerate(zip(points, points[1:] + points[:1]), 1):
        mx = (x1 + x2) / 2
        my = (y1 + y2) / 2
        labels.append(f'<text class="edge" x="{mx:.3f}" y="{my:.3f}" text-anchor="middle">E{i}</text>')
    return labels


def _angle_labels(points: list[tuple[float, float]]) -> list[str]:
    labels = []
    cx = sum(x for x, _ in points) / len(points)
    cy = sum(y for _, y in points) / len(points)
    for i, p in enumerate(points):
        prev = points[i - 1]
        nxt = points[(i + 1) % len(points)]
        angle = _corner_angle(prev, p, nxt)
        dx = p[0] - cx
        dy = p[1] - cy
        length = hypot(dx, dy) or 1
        labels.append(f'<text class="tiny" x="{p[0] + dx / length * 5:.3f}" y="{p[1] + dy / length * 5:.3f}" text-anchor="middle">{angle:.0f}deg</text>')
    return labels


def _dimension_labels(points: list[tuple[float, float]]) -> list[str]:
    min_x, min_y, max_x, max_y = polygon_bounds(points)
    y = max_y + 7
    x = max_x + 7
    return [
        f'<line class="dim" x1="{min_x:.3f}" y1="{y:.3f}" x2="{max_x:.3f}" y2="{y:.3f}"/>',
        f'<text class="dimtext" x="{(min_x + max_x) / 2:.3f}" y="{y + 4:.3f}" text-anchor="middle">{max_x - min_x:.1f} mm</text>',
        f'<line class="dim" x1="{x:.3f}" y1="{min_y:.3f}" x2="{x:.3f}" y2="{max_y:.3f}"/>',
        f'<text class="dimtext" x="{x + 3:.3f}" y="{(min_y + max_y) / 2:.3f}">{max_y - min_y:.1f} mm</text>',
    ]


def _hole_shapes(holes: list[dict]) -> list[str]:
    rows = []
    for hole in holes:
        if hole.get("type") == "CIRCLE":
            rows.append(f'<circle class="hole" cx="{hole["x"]:.3f}" cy="{hole["y"]:.3f}" r="{hole["r"]:.3f}"/>')
        elif hole.get("type") == "RECTANGLE":
            rows.append(f'<rect class="hole" x="{hole["x"]:.3f}" y="{hole["y"]:.3f}" width="{hole["w"]:.3f}" height="{hole["h"]:.3f}"/>')
    return rows


def _corner_angle(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> float:
    ab = (a[0] - b[0], a[1] - b[1])
    cb = (c[0] - b[0], c[1] - b[1])
    denom = (hypot(*ab) * hypot(*cb)) or 1
    dot = max(-1, min(1, (ab[0] * cb[0] + ab[1] * cb[1]) / denom))
    return degrees(acos(dot))


def export_project_json(path: str | Path, state: dict, panels: list[Panel2D]) -> None:
    payload = {"state": state, "panels": [p.__dict__ for p in panels]}
    Path(path).write_text(json.dumps(payload, indent=2), encoding="utf-8")


def export_bom_csv(path: str | Path, panels: list[Panel2D]) -> None:
    counts: dict[tuple[str, str, float], int] = {}
    for p in panels:
        key = (p.panel_id, p.material, p.thickness)
        counts[key] = counts.get(key, 0) + p.quantity
    with Path(path).open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "material", "thickness_mm", "quantity"])
        for (panel_id, material, thickness), quantity in counts.items():
            writer.writerow([panel_id, material, thickness, quantity])


def export_dxf(path: str | Path, panels: list[Panel2D]) -> None:
    lines = ["0", "SECTION", "2", "ENTITIES"]
    for p in panels:
        pts = p.points + [p.points[0]]
        for (x1, y1), (x2, y2) in zip(pts, pts[1:]):
            lines += ["0", "LINE", "8", "CUT", "10", str(x1), "20", str(y1), "11", str(x2), "21", str(y2)]
    lines += ["0", "ENDSEC", "0", "EOF"]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def export_pdf(path: str | Path, panels: list[Panel2D], width: float, height: float) -> None:
    mm_to_pt = 72 / 25.4
    page_w = width * mm_to_pt
    page_h = height * mm_to_pt
    commands = ["0.3 w", "1 0 0 RG"]
    for panel in panels:
        pts = [(x * mm_to_pt, page_h - y * mm_to_pt) for x, y in panel.points]
        if not pts:
            continue
        commands.append(f"{pts[0][0]:.3f} {pts[0][1]:.3f} m")
        for x, y in pts[1:]:
            commands.append(f"{x:.3f} {y:.3f} l")
        commands.append("h S")
        label_x, label_y = pts[0]
        commands.append("0 0 0 rg")
        commands.append(f"BT /F1 8 Tf {label_x:.3f} {label_y - 10:.3f} Td ({_pdf_escape(panel.panel_id)}) Tj ET")
        commands.append("1 0 0 RG")
        for hole in panel.holes:
            _pdf_hole(commands, hole, mm_to_pt, page_h)
    _write_pdf(path, page_w, page_h, "\n".join(commands).encode("ascii"))


def _pdf_hole(commands: list[str], hole: dict, scale: float, page_h: float) -> None:
    commands.append("0 0 1 RG")
    if hole.get("type") == "RECTANGLE":
        x = hole["x"] * scale
        y = page_h - (hole["y"] + hole["h"]) * scale
        commands.append(f"{x:.3f} {y:.3f} {hole['w'] * scale:.3f} {hole['h'] * scale:.3f} re S")
    elif hole.get("type") == "CIRCLE":
        from math import cos, pi, sin

        # ponytail: 12-sided circle approximation; swap for Beziers if print fidelity needs it.
        cx = hole["x"] * scale
        cy = page_h - hole["y"] * scale
        r = hole["r"] * scale
        pts = [(cx + cos(i * pi / 6) * r, cy + sin(i * pi / 6) * r) for i in range(12)]
        commands.append(f"{pts[0][0]:.3f} {pts[0][1]:.3f} m")
        for x, y in pts[1:]:
            commands.append(f"{x:.3f} {y:.3f} l")
        commands.append("h S")
    commands.append("1 0 0 RG")


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _write_pdf(path: str | Path, width: float, height: float, stream: bytes) -> None:
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {width:.3f} {height:.3f}] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>".encode("ascii"),
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, 1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode("ascii"))
        out.write(obj)
        out.write(b"\nendobj\n")
    xref = out.tell()
    out.write(f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode("ascii"))
    for offset in offsets:
        out.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    out.write(f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode("ascii"))
    Path(path).write_bytes(out.getvalue())
